# If serverUrl.isEmpty() ? embedded mode : tournament mode
# If tournament mode without tournamentUrl : connect to sim directly
visualizer:
    mode: research
    connect:
        jmsUrl: tcp://localhost:61616
